TRUNCATE TABLE article CASCADE;
TRUNCATE TABLE magasin CASCADE;
TRUNCATE TABLE unite CASCADE;
TRUNCATE TABLE article_unite CASCADE;
TRUNCATE TABLE entree CASCADE;
TRUNCATE TABLE mouvement CASCADE;
TRUNCATE TABLE sortie CASCADE;
TRUNCATE TABLE validation_mouvement CASCADE;